"""empty message

Revision ID: 2fd596598ae6
Revises: f9cbed5b03bb
Create Date: 2024-04-19 19:42:05.220572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd596598ae6'
down_revision = 'f9cbed5b03bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_ko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_ko')
    # ### end Alembic commands ###
